export const vocabulary = {
  ru: 0,
  ua: 1,
  en: 2,
  filmoteka: ['Фильмотека', 'Фільмотека', 'Filmoteka'],
  home: ['Главная', 'Головна', 'Home'],
  library: ['Моя библиотека', 'Моя бібліотека', 'My library'],
  watched: ['Смотрели', 'Дивились', 'Watched'],
  queue: ['Очередь', 'Черга', 'Queue'],
  search: ['Поиск фильмов...', 'Пошук фільмів...', 'Search Movies...'],
  errorSearchMovie: [
    'Не найдено. Введите правильное название фильма и повторите попытку!',
    'Не знайдено. Введіть правильну назву фільму та повторіть спробу!',
    'Search result not successful. Enter the correct movie name and retry!',
  ],
  errorEmptySerch: ['Надо написать что-нибудь!', 'Треба написати щось!', 'Please write something!'],
  mVote: ['Оценка/Голосов:', 'Оцінка/Голосів:', 'Vote/Votes:'],
  mPopularity: ['Популяроность:', 'Популярність:', 'Popularity:'],
  mTitle: ['Оригинальное название:', 'Оригінальна назва:', 'Original Title:'],
  mGenre: ['Жанр:', 'Жанр:', 'Genre:'],
  mAbout: ['О фильме', 'Про фільм', 'About'],
  mWatched: ['добавить к просмотренным', 'додати до переглянутого', 'add to watched'],
  mQueue: ['добавить в очередь', 'додати до черги', 'add to queue'],
  mWatchedRemove: ['Удалить из просмотренных', 'Вилучити з переглянутих', 'Remove from watched'],
  mQueueRemove: ['Удалить из очереди', 'Вилучити з черги', 'Remove from queued'],
};
